# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_monthjournal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day1',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day10',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day11',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day12',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day13',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day14',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day15',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day16',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day17',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day18',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day19',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day2',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day20',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day21',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day22',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day23',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day24',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day25',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day26',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day27',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day28',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day29',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day3',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day30',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day31',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day4',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day5',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day6',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day7',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day8',
        ),
        migrations.RemoveField(
            model_name='monthjournal',
            name='present_day9',
        ),
    ]
