# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20151026_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthjournal',
            name='present_day1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day21',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day22',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day23',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day25',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day26',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day27',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day28',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day29',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day31',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='present_day9',
            field=models.BooleanField(default=False),
        ),
    ]
